accounts:
  - name: alice
    coins: ["2000atom", "1000iris", "1000osmo", "1000regen", "1000dvpn", "1000xprt", "1000cro", "1000akt", "200000000stake"]
  - name: bob
    coins: ["2000atom", "1000iris", "1000osmo", "1000regen", "1000dvpn", "1000xprt", "1000cro", "1000akt", "200000000stake"]
validator:
  name: alice
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
