// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: wayne/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the wayne module's genesis state.
type GenesisState struct {
	Params                Params             `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	PoolList              []Pool             `protobuf:"bytes,2,rep,name=poolList,proto3" json:"poolList"`
	PoolCount             uint64             `protobuf:"varint,3,opt,name=poolCount,proto3" json:"poolCount,omitempty"`
	DepositList           []Deposit          `protobuf:"bytes,4,rep,name=depositList,proto3" json:"depositList"`
	DepositCount          uint64             `protobuf:"varint,5,opt,name=depositCount,proto3" json:"depositCount,omitempty"`
	BorrowList            []Borrow           `protobuf:"bytes,6,rep,name=borrowList,proto3" json:"borrowList"`
	BorrowCount           uint64             `protobuf:"varint,7,opt,name=borrowCount,proto3" json:"borrowCount,omitempty"`
	UserList              []User             `protobuf:"bytes,8,rep,name=userList,proto3" json:"userList"`
	UserCount             uint64             `protobuf:"varint,9,opt,name=userCount,proto3" json:"userCount,omitempty"`
	InterfaceAprList      []InterfaceApr     `protobuf:"bytes,10,rep,name=interfaceAprList,proto3" json:"interfaceAprList"`
	InterfaceAprCount     uint64             `protobuf:"varint,11,opt,name=interfaceAprCount,proto3" json:"interfaceAprCount,omitempty"`
	LoadPoolResponseList  []LoadPoolResponse `protobuf:"bytes,12,rep,name=loadPoolResponseList,proto3" json:"loadPoolResponseList"`
	LoadPoolResponseCount uint64             `protobuf:"varint,13,opt,name=loadPoolResponseCount,proto3" json:"loadPoolResponseCount,omitempty"`
	WithdrawList          []Withdraw         `protobuf:"bytes,14,rep,name=withdrawList,proto3" json:"withdrawList"`
	WithdrawCount         uint64             `protobuf:"varint,15,opt,name=withdrawCount,proto3" json:"withdrawCount,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_f92d6fa75d77cb4f, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetPoolList() []Pool {
	if m != nil {
		return m.PoolList
	}
	return nil
}

func (m *GenesisState) GetPoolCount() uint64 {
	if m != nil {
		return m.PoolCount
	}
	return 0
}

func (m *GenesisState) GetDepositList() []Deposit {
	if m != nil {
		return m.DepositList
	}
	return nil
}

func (m *GenesisState) GetDepositCount() uint64 {
	if m != nil {
		return m.DepositCount
	}
	return 0
}

func (m *GenesisState) GetBorrowList() []Borrow {
	if m != nil {
		return m.BorrowList
	}
	return nil
}

func (m *GenesisState) GetBorrowCount() uint64 {
	if m != nil {
		return m.BorrowCount
	}
	return 0
}

func (m *GenesisState) GetUserList() []User {
	if m != nil {
		return m.UserList
	}
	return nil
}

func (m *GenesisState) GetUserCount() uint64 {
	if m != nil {
		return m.UserCount
	}
	return 0
}

func (m *GenesisState) GetInterfaceAprList() []InterfaceApr {
	if m != nil {
		return m.InterfaceAprList
	}
	return nil
}

func (m *GenesisState) GetInterfaceAprCount() uint64 {
	if m != nil {
		return m.InterfaceAprCount
	}
	return 0
}

func (m *GenesisState) GetLoadPoolResponseList() []LoadPoolResponse {
	if m != nil {
		return m.LoadPoolResponseList
	}
	return nil
}

func (m *GenesisState) GetLoadPoolResponseCount() uint64 {
	if m != nil {
		return m.LoadPoolResponseCount
	}
	return 0
}

func (m *GenesisState) GetWithdrawList() []Withdraw {
	if m != nil {
		return m.WithdrawList
	}
	return nil
}

func (m *GenesisState) GetWithdrawCount() uint64 {
	if m != nil {
		return m.WithdrawCount
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "cosmonaut.wayne.wayne.GenesisState")
}

func init() { proto.RegisterFile("wayne/genesis.proto", fileDescriptor_f92d6fa75d77cb4f) }

var fileDescriptor_f92d6fa75d77cb4f = []byte{
	// 509 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x63, 0x1a, 0x42, 0xbb, 0x4e, 0xa1, 0x2c, 0xa9, 0x14, 0x02, 0xb8, 0x51, 0x41, 0x22,
	0x07, 0xe4, 0x48, 0x85, 0x1b, 0xe2, 0x40, 0x8a, 0x40, 0x95, 0x7a, 0x40, 0x41, 0x15, 0x12, 0x97,
	0x68, 0x93, 0x2c, 0xa9, 0xa5, 0xc4, 0x63, 0x79, 0x37, 0x0a, 0x7d, 0x0b, 0x1e, 0xab, 0xc7, 0x1e,
	0x39, 0x21, 0x94, 0x1c, 0x78, 0x0d, 0xb4, 0x33, 0xe3, 0x60, 0xb7, 0x71, 0x2f, 0xc9, 0xee, 0xcc,
	0xfc, 0xf3, 0xfd, 0x9e, 0xdd, 0x15, 0x8f, 0x16, 0xea, 0x22, 0xd6, 0xdd, 0x89, 0x8e, 0xb5, 0x89,
	0x4c, 0x98, 0xa4, 0x60, 0x41, 0xee, 0x8f, 0xc0, 0xcc, 0x20, 0x56, 0x73, 0x1b, 0x62, 0x9a, 0x7e,
	0x5b, 0x8d, 0x09, 0x4c, 0x00, 0x2b, 0xba, 0x6e, 0x45, 0xc5, 0x2d, 0x49, 0x1d, 0x12, 0x95, 0xaa,
	0x19, 0x37, 0x68, 0xed, 0x71, 0x0c, 0x60, 0xca, 0x11, 0xe6, 0x8c, 0x75, 0x02, 0x26, 0xb2, 0x45,
	0xe9, 0x10, 0xd2, 0x14, 0x16, 0x45, 0xe9, 0xdc, 0xe8, 0x94, 0x23, 0x8f, 0x29, 0x12, 0xc5, 0x56,
	0xa7, 0xdf, 0xd5, 0x48, 0x0f, 0x54, 0x92, 0xa5, 0x02, 0x4a, 0x4d, 0x41, 0x8d, 0x07, 0x0e, 0x36,
	0x48, 0xb5, 0x49, 0x20, 0x36, 0x9a, 0xf3, 0x0d, 0xca, 0x2f, 0x22, 0x7b, 0x3e, 0x4e, 0x15, 0x23,
	0x0e, 0xff, 0xd6, 0x44, 0xfd, 0x13, 0x7d, 0xf0, 0x17, 0xab, 0xac, 0x96, 0x6f, 0x45, 0x8d, 0xec,
	0x37, 0xbd, 0xb6, 0xd7, 0xf1, 0x8f, 0x9e, 0x85, 0x1b, 0x07, 0x10, 0x7e, 0xc6, 0xa2, 0x5e, 0xf5,
	0xf2, 0xf7, 0x41, 0xa5, 0xcf, 0x12, 0xf9, 0x4e, 0x6c, 0x3b, 0xf4, 0x69, 0x64, 0x6c, 0xf3, 0x4e,
	0x7b, 0xab, 0xe3, 0x1f, 0x3d, 0x29, 0x93, 0x03, 0x4c, 0x59, 0xbc, 0x96, 0xc8, 0xa7, 0x62, 0xc7,
	0xad, 0x8f, 0x61, 0x1e, 0xdb, 0xe6, 0x56, 0xdb, 0xeb, 0x54, 0xfb, 0xff, 0x03, 0xf2, 0xa3, 0xf0,
	0x79, 0x64, 0xd8, 0xbf, 0x8a, 0xfd, 0x83, 0x92, 0xfe, 0x1f, 0xa8, 0x92, 0x11, 0x79, 0xa1, 0x3c,
	0x14, 0x75, 0xde, 0x12, 0xe8, 0x2e, 0x82, 0x0a, 0x31, 0x79, 0x2c, 0x04, 0x9d, 0x04, 0xa2, 0x6a,
	0x88, 0x2a, 0x9b, 0x44, 0x0f, 0x0b, 0x99, 0x94, 0x93, 0xc9, 0xb6, 0xf0, 0x69, 0x47, 0x9c, 0x7b,
	0xc8, 0xc9, 0x87, 0xdc, 0xbc, 0xdc, 0xe1, 0x22, 0x64, 0xfb, 0xd6, 0x79, 0x9d, 0x19, 0x9d, 0x66,
	0xf3, 0xca, 0x24, 0x6e, 0x5e, 0x6e, 0x4d, 0xed, 0x77, 0x68, 0x5e, 0xeb, 0x80, 0x3c, 0x13, 0x7b,
	0xeb, 0x7b, 0xf2, 0x3e, 0x21, 0x88, 0x40, 0xc8, 0xf3, 0x12, 0xc8, 0x49, 0xae, 0x9c, 0x61, 0x37,
	0x5a, 0xc8, 0x57, 0xe2, 0x61, 0x3e, 0x46, 0x70, 0x1f, 0xe1, 0x37, 0x13, 0x52, 0x89, 0x86, 0xbb,
	0x91, 0xee, 0xb8, 0xfb, 0x7c, 0x1f, 0xd1, 0x48, 0x1d, 0x8d, 0xbc, 0x2c, 0x31, 0x72, 0x7a, 0x4d,
	0xc2, 0x66, 0x36, 0xb6, 0x92, 0x6f, 0xc4, 0xfe, 0xf5, 0x38, 0x99, 0xda, 0x45, 0x53, 0x9b, 0x93,
	0xf2, 0x44, 0xd4, 0xb3, 0xa7, 0x80, 0x86, 0xee, 0xa3, 0xa1, 0x83, 0x12, 0x43, 0x5f, 0xb9, 0x94,
	0x8d, 0x14, 0xa4, 0xf2, 0x85, 0xd8, 0xcd, 0xf6, 0x04, 0x7e, 0x80, 0xe0, 0x62, 0xb0, 0xd7, 0xbb,
	0x5c, 0x06, 0xde, 0xd5, 0x32, 0xf0, 0xfe, 0x2c, 0x03, 0xef, 0xe7, 0x2a, 0xa8, 0x5c, 0xad, 0x82,
	0xca, 0xaf, 0x55, 0x50, 0xf9, 0xd6, 0x99, 0x44, 0xf6, 0x7c, 0x3e, 0x0c, 0x47, 0x30, 0xeb, 0xae,
	0xf1, 0x5d, 0x7a, 0xae, 0x3f, 0xf8, 0xdf, 0x5e, 0x24, 0xda, 0x0c, 0x6b, 0xf8, 0x68, 0x5f, 0xff,
	0x0b, 0x00, 0x00, 0xff, 0xff, 0x68, 0x96, 0xfb, 0xcf, 0xaa, 0x04, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.WithdrawCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.WithdrawCount))
		i--
		dAtA[i] = 0x78
	}
	if len(m.WithdrawList) > 0 {
		for iNdEx := len(m.WithdrawList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.WithdrawList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x72
		}
	}
	if m.LoadPoolResponseCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.LoadPoolResponseCount))
		i--
		dAtA[i] = 0x68
	}
	if len(m.LoadPoolResponseList) > 0 {
		for iNdEx := len(m.LoadPoolResponseList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.LoadPoolResponseList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x62
		}
	}
	if m.InterfaceAprCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.InterfaceAprCount))
		i--
		dAtA[i] = 0x58
	}
	if len(m.InterfaceAprList) > 0 {
		for iNdEx := len(m.InterfaceAprList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.InterfaceAprList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if m.UserCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.UserCount))
		i--
		dAtA[i] = 0x48
	}
	if len(m.UserList) > 0 {
		for iNdEx := len(m.UserList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.UserList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if m.BorrowCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.BorrowCount))
		i--
		dAtA[i] = 0x38
	}
	if len(m.BorrowList) > 0 {
		for iNdEx := len(m.BorrowList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BorrowList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if m.DepositCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.DepositCount))
		i--
		dAtA[i] = 0x28
	}
	if len(m.DepositList) > 0 {
		for iNdEx := len(m.DepositList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DepositList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.PoolCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.PoolCount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.PoolList) > 0 {
		for iNdEx := len(m.PoolList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PoolList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.PoolList) > 0 {
		for _, e := range m.PoolList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.PoolCount != 0 {
		n += 1 + sovGenesis(uint64(m.PoolCount))
	}
	if len(m.DepositList) > 0 {
		for _, e := range m.DepositList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.DepositCount != 0 {
		n += 1 + sovGenesis(uint64(m.DepositCount))
	}
	if len(m.BorrowList) > 0 {
		for _, e := range m.BorrowList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.BorrowCount != 0 {
		n += 1 + sovGenesis(uint64(m.BorrowCount))
	}
	if len(m.UserList) > 0 {
		for _, e := range m.UserList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.UserCount != 0 {
		n += 1 + sovGenesis(uint64(m.UserCount))
	}
	if len(m.InterfaceAprList) > 0 {
		for _, e := range m.InterfaceAprList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.InterfaceAprCount != 0 {
		n += 1 + sovGenesis(uint64(m.InterfaceAprCount))
	}
	if len(m.LoadPoolResponseList) > 0 {
		for _, e := range m.LoadPoolResponseList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.LoadPoolResponseCount != 0 {
		n += 1 + sovGenesis(uint64(m.LoadPoolResponseCount))
	}
	if len(m.WithdrawList) > 0 {
		for _, e := range m.WithdrawList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.WithdrawCount != 0 {
		n += 1 + sovGenesis(uint64(m.WithdrawCount))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolList = append(m.PoolList, Pool{})
			if err := m.PoolList[len(m.PoolList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolCount", wireType)
			}
			m.PoolCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DepositList = append(m.DepositList, Deposit{})
			if err := m.DepositList[len(m.DepositList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositCount", wireType)
			}
			m.DepositCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DepositCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BorrowList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BorrowList = append(m.BorrowList, Borrow{})
			if err := m.BorrowList[len(m.BorrowList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BorrowCount", wireType)
			}
			m.BorrowCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BorrowCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserList = append(m.UserList, User{})
			if err := m.UserList[len(m.UserList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserCount", wireType)
			}
			m.UserCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UserCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InterfaceAprList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InterfaceAprList = append(m.InterfaceAprList, InterfaceApr{})
			if err := m.InterfaceAprList[len(m.InterfaceAprList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InterfaceAprCount", wireType)
			}
			m.InterfaceAprCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InterfaceAprCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LoadPoolResponseList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LoadPoolResponseList = append(m.LoadPoolResponseList, LoadPoolResponse{})
			if err := m.LoadPoolResponseList[len(m.LoadPoolResponseList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LoadPoolResponseCount", wireType)
			}
			m.LoadPoolResponseCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LoadPoolResponseCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WithdrawList = append(m.WithdrawList, Withdraw{})
			if err := m.WithdrawList[len(m.WithdrawList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawCount", wireType)
			}
			m.WithdrawCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WithdrawCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
